# Generated by Django 4.2.20 on 2025-03-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
